server:
  port: 0
  servlet:
    context-path: /ms-auth
    #http://{nome_host}:{porta}/auth/restoDellUrl

spring:
  application:
    name: ms-auth

  datasource:
    url: jdbc:mariadb://localhost:3306/ms_auth?createDatabaseIfNotExist=true&autoReconnect=true&useSLL=false
    username: root
    password:


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: false


logging:
  level:
    it.cgmconsulting.auth: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework: info
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
  client:
    service-url:
      default-zone: localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: info, health
  info:
    java.enabled: true
    os.enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans