server:
  port: 8761 #porta predefinita

eureka:
  instance:
    hostname: localhost #www.pippo.org se fosse sul cloud
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.85
    renewal-threshold-update-interval-ms: 900000
    enable-self-preservation: true